/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswing;

import chungkhoan.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.Random;
/**
 *
 * @author Hai Duong
 */
public class Frame1 extends javax.swing.JFrame {
    private final String s1 = "Cổ phiếu trong ngày";
    private final String s2 = "Cổ phiếu giảm giá";
    private final String s3 = "Cổ phiếu có mức GD cao";
    private DefaultComboBoxModel model; 
    Random a = new Random();
    
 

    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        init();
    }
    private void init(){
            model = new DefaultComboBoxModel();
            model.addElement(s1);
            model.addElement(s2);
            model.addElement(s3);
            jBox.setModel(model);
        }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 200));
        setSize(new java.awt.Dimension(1200, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jBox.setAutoscrolls(true);
        jBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Text.setColumns(20);
        Text.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        jButton2.setText("LƯU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(470, 470, 470))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBox, jButton1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       if(null != (String)jBox.getSelectedItem())switch ((String)jBox.getSelectedItem()) {
            case s1:
                switch (a.nextInt(4)){
                    case 0 : 
                        Text.append("\n"+new MauCau5().getCau()); 
                        break; 
                    case 1 :
                        Text.append("\n"+new MauCau6().getCau());
                        break;  
                    case 2 :
                        Text.append("\n"+new MauCau7().getCau()); 
                        break;
                    case 3 :
                        Text.append("\n"+new MauCau8().getCau()); 
                        break;
                
                }
                
                break;
            case s2:
                switch (a.nextInt(5)){
                    case 0 : 
                        Text.append("\n"+new MauCau3().getCau()); 
                        break; 
                    case 1 :
                        Text.append("\n"+new MauCau4().getCau());
                        break;  
                    case 2 :
                        Text.append("\n"+new MauCau6().getCau()); 
                        break;
                    case 3 :
                        Text.append("\n"+new MauCau8().getCau()); 
                        break;
                    case 4:     
                        Text.append("\n"+new MauCau9().getCau()); 
                        break;
                }
                break;
            case s3:
                switch (a.nextInt(3)){
                    case 0 : 
                        Text.append("\n"+new MauCau1().getCau()); 
                        break; 
                    case 1 :
                        Text.append("\n"+new MauCau2().getCau());
                        break;  
                    case 2 :
                        Text.append("\n"+new MauCau10().getCau()); 
                        break;       
                }
                
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      JOptionPane.showMessageDialog(null,"Bạn có muốn lưu file text không ?","EXIT",JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        File out = new File("output.txt");
        out.createNewFile();
        FileWriter fr = new FileWriter(out);
        fr.append(Text.getText());
        fr.close();
        }
        catch(IOException e){
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Text;
    private javax.swing.JComboBox<String> jBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
